spring.datasource.url=jdbc:postgresql://190.106.91.44:5432/prod_db
spring.datasource.username=${DB_USERNAME:sys_db_user}
spring.datasource.password=${DB_PASSWORD:H6l17&bbssMb} 
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false


# Editar as configurações posteriormente